// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-15/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-15",
  frameClassName: "theme15-wrapper bg-[#F8FAFC] dark:bg-[#0F172A]",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider","statistics","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Highlights",
    component: "Highlights",
    slices: ["statistics","program"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Highlights/Highlights").then((m) => m.Highlights),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "features",
    kind: "features",
    label: "Why Choose",
    component: "WhyChoose",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/WhyChoose/WhyChoose").then((m) => m.WhyChoose),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Campus Life",
    component: "CampusLife",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/CampusLife/CampusLife").then((m) => m.CampusLife),
  },
  {
    id: "admission",
    kind: "admission",
    label: "Admission Process",
    component: "AdmissionProcess",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Admissions/AdmissionProcess").then((m) => m.AdmissionProcess),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "news",
    kind: "news",
    label: "News And Events",
    component: "NewsAndEvents",
    slices: ["news","event"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/News/NewsAndEvents").then((m) => m.NewsAndEvents),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Accreditation",
    component: "Accreditation",
    slices: ["client"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/Accreditation/Accreditation").then((m) => m.Accreditation),
  },
  {
    id: "gallery-2",
    kind: "gallery",
    label: "Virtual Tour",
    component: "VirtualTour",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/VirtualTour/VirtualTour").then((m) => m.VirtualTour),
  },
  {
    id: "cta",
    kind: "cta",
    label: "Call To Action",
    component: "CallToAction",
    slices: ["layout"],
    load: () => import("@edn/site-themes/Theme/Theme-15/components/CTA/CallToAction").then((m) => m.CallToAction),
  },
  ],
};

export default manifest;
