// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-13/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-13",
  frameClassName: "t13 relative min-h-screen overflow-x-hidden",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Statistics",
    component: "Statistics",
    slices: ["statistics"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Statistics/Statistics").then((m) => m.Statistics),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs","layout","slider"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/About/About").then((m) => m.About),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "notices",
    kind: "notices",
    label: "Notice And Events",
    component: "NoticeAndEvents",
    slices: ["notice","event","news"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Notice/NoticeAndEvents").then((m) => m.NoticeAndEvents),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facility",
    component: "Facility",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Facility/Facility").then((m) => m.Facility),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Partners",
    component: "Partners",
    slices: ["client"],
    load: () => import("@edn/site-themes/Theme/Theme-13/components/Partners/Partners").then((m) => m.Partners),
  },
  ],
};

export default manifest;
