// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-12/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-12",
  frameClassName: "min-h-screen bg-slate-50 dark:bg-slate-950",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["portfolio"],
    load: () => import("@edn/site-themes/Theme/Theme-12/components/hero/Hero").then((m) => m.Hero),
  },
  ],
};

export default manifest;
