// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-7/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-7",
  frameClassName: "relative min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 selection:bg-emerald-100 dark:selection:bg-emerald-900/30 selection:text-emerald-900 dark:selection:text-emerald-100 overflow-x-hidden font-sans",
  mainClassName: "theme7-wrapper relative z-10",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs","layout","statistics","home","album","slider"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/About/About").then((m) => m.About),
  },
  {
    id: "team",
    kind: "team",
    label: "Board Message",
    component: "BoardMessage",
    slices: ["boardMessage"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/BoardMessage/BoardMessage").then((m) => m.BoardMessage),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "events",
    kind: "events",
    label: "Events",
    component: "Events",
    slices: ["event"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Events/Events").then((m) => m.Events),
  },
  {
    id: "admission",
    kind: "admission",
    label: "Admission",
    component: "Admission",
    slices: ["layout"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Admission/Admission").then((m) => m.Admission),
  },
  {
    id: "team-2",
    kind: "team",
    label: "Faculty",
    component: "Faculty",
    slices: ["board"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Faculty/Faculty").then((m) => m.Faculty),
  },
  {
    id: "news",
    kind: "news",
    label: "Blog",
    component: "Blog",
    slices: ["blog","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Blog/Blog").then((m) => m.Blog),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album","home"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facilities",
    component: "Facilities",
    slices: ["facility","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Facilities/Facilities").then((m) => m.Facilities),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Partners",
    component: "Partners",
    slices: ["client"],
    load: () => import("@edn/site-themes/Theme/Theme-7/components/Partners/Partners").then((m) => m.Partners),
  },
  ],
};

export default manifest;
