// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-6/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-6",
  frameClassName: "relative min-h-screen overflow-x-hidden bg-white font-sans text-slate-900 selection:bg-blue-100 selection:text-blue-900",
  mainClassName: "theme6-main relative z-10",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["layout","slider","facility"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs","layout","statistics"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/About/About").then((m) => m.About),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Campus Life",
    component: "CampusLife",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/Facilities/Facilities").then((m) => m.Facilities),
  },
  {
    id: "features",
    kind: "features",
    label: "Why Choose Us",
    component: "WhyChooseUs",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/Admission/Admission").then((m) => m.Admission),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "news",
    kind: "news",
    label: "News",
    component: "News",
    slices: ["event"],
    load: () => import("@edn/site-themes/Theme/Theme-6/components/News/News").then((m) => m.News),
  },
  ],
};

export default manifest;
