// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-8/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-8",
  frameClassName: "relative min-h-screen bg-[#FDFCF8] dark:bg-slate-950 text-slate-900 dark:text-slate-50 selection:bg-indigo-100 dark:selection:bg-indigo-900/30 selection:text-indigo-900 dark:selection:text-indigo-100 overflow-x-hidden font-sans",
  mainClassName: "theme8-wrapper relative z-10",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/About/About").then((m) => m.About),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Statistics",
    component: "Statistics",
    slices: ["statistics"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Statistics/Statistics").then((m) => m.Statistics),
  },
  {
    id: "notices",
    kind: "notices",
    label: "Notice",
    component: "Notice",
    slices: ["notice","event","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Notice/Notice").then((m) => m.Notice),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "events",
    kind: "events",
    label: "Events",
    component: "Events",
    slices: ["event"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Events/Events").then((m) => m.Events),
  },
  {
    id: "admission",
    kind: "admission",
    label: "Admission",
    component: "Admission",
    slices: ["layout"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Admission/Admission").then((m) => m.Admission),
  },
  {
    id: "team",
    kind: "team",
    label: "Faculty",
    component: "Faculty",
    slices: ["board"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Faculty/Faculty").then((m) => m.Faculty),
  },
  {
    id: "news",
    kind: "news",
    label: "Blog",
    component: "Blog",
    slices: ["blog"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Blog/Blog").then((m) => m.Blog),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facilities",
    component: "Facilities",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Facilities/Facilities").then((m) => m.Facilities),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Partners",
    component: "Partners",
    slices: ["client"],
    load: () => import("@edn/site-themes/Theme/Theme-8/components/Partners/Partners").then((m) => m.Partners),
  },
  ],
};

export default manifest;
