// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-18/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-18",
  frameClassName: "theme18-wrapper relative isolate min-h-screen bg-(--t18-void)",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Trusted",
    component: "Trusted",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Trusted/Trusted").then((m) => m.Trusted),
  },
  {
    id: "features",
    kind: "features",
    label: "Ecosystem",
    component: "Ecosystem",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Ecosystem/Ecosystem").then((m) => m.Ecosystem),
  },
  {
    id: "about",
    kind: "about",
    label: "Story",
    component: "Story",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Story/Story").then((m) => m.Story),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Products",
    component: "Products",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Products/Products").then((m) => m.Products),
  },
  {
    id: "features-2",
    kind: "features",
    label: "Dashboard",
    component: "Dashboard",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Dashboard/Dashboard").then((m) => m.Dashboard),
  },
  {
    id: "features-3",
    kind: "features",
    label: "Mobile Showcase",
    component: "MobileShowcase",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Mobile/MobileShowcase").then((m) => m.MobileShowcase),
  },
  {
    id: "features-4",
    kind: "features",
    label: "Features",
    component: "Features",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Features/Features").then((m) => m.Features),
  },
  {
    id: "events",
    kind: "events",
    label: "Timeline",
    component: "Timeline",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Timeline/Timeline").then((m) => m.Timeline),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "partners-2",
    kind: "partners",
    label: "Awards",
    component: "Awards",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Awards/Awards").then((m) => m.Awards),
  },
  {
    id: "faq",
    kind: "faq",
    label: "FAQ",
    component: "FAQ",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/FAQ/FAQ").then((m) => m.FAQ),
  },
  {
    id: "contact",
    kind: "contact",
    label: "Contact",
    component: "Contact",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-18/components/Contact/Contact").then((m) => m.Contact),
  },
  ],
};

export default manifest;
