// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-5/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-5",
  frameClassName: "",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "hero",
    component: "hero",
    slices: ["layout","slider"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "notices",
    kind: "notices",
    label: "notice",
    component: "notice",
    slices: ["notice"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Notice/Notice").then((m) => m.Notice),
  },
  {
    id: "about",
    kind: "about",
    label: "about",
    component: "about",
    slices: ["aboutUs","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/About/About").then((m) => m.About),
  },
  {
    id: "programs",
    kind: "programs",
    label: "programs",
    component: "programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "events",
    kind: "events",
    label: "events",
    component: "events",
    slices: ["event","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Events/Events").then((m) => m.Events),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "gallery",
    component: "gallery",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "facilities",
    component: "facilities",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Facilities/Facilities").then((m) => m.Facilities),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "testimonials",
    component: "testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "news",
    kind: "news",
    label: "blog",
    component: "blog",
    slices: ["blog"],
    load: () => import("@edn/site-themes/Theme/Theme-5/components/Blog/Blog").then((m) => m.Blog),
  },
  ],
};

export default manifest;
