// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-9/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-9",
  frameClassName: "relative min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-50 selection:bg-primary/20 selection:text-primary overflow-x-hidden font-sans",
  mainClassName: "theme9-wrapper relative z-10",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/About/About").then((m) => m.About),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Statistics",
    component: "Statistics",
    slices: ["statistics"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Statistics/Statistics").then((m) => m.Statistics),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facility",
    component: "Facility",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Facility/Facility").then((m) => m.Facility),
  },
  {
    id: "notices",
    kind: "notices",
    label: "Notice And Events",
    component: "NoticeAndEvents",
    slices: ["notice","event","layout"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Notice/NoticeAndEvents").then((m) => m.NoticeAndEvents),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Campus Life",
    component: "CampusLife",
    slices: ["blog"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/CampusLife/CampusLife").then((m) => m.CampusLife),
  },
  {
    id: "gallery-2",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-9/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  ],
};

export default manifest;
