// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-11/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-11",
  frameClassName: "",
  mainClassName: "",
  sections: [
  {
    id: "generic",
    kind: "generic",
    label: "Backdrop",
    component: "Backdrop",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Backdrop").then((m) => m.Backdrop),
  },
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["layout","aboutUs"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/About/About").then((m) => m.About),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Partners",
    component: "Partners",
    slices: ["client"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Partners/Partners").then((m) => m.Partners),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Statistics",
    component: "Statistics",
    slices: ["statistics"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Statistics/Statistics").then((m) => m.Statistics),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facility",
    component: "Facility",
    slices: ["facility"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Facility/Facility").then((m) => m.Facility),
  },
  {
    id: "notices",
    kind: "notices",
    label: "Notice And Events",
    component: "NoticeAndEvents",
    slices: ["notice","event"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Notice/NoticeAndEvents").then((m) => m.NoticeAndEvents),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    className: "theme11-wrapper relative z-10",
    load: () => import("@edn/site-themes/Theme/Theme-11/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  ],
};

export default manifest;
