// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-19/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-19",
  frameClassName: "theme19-wrapper bg-(--t19-linen)",
  mainClassName: "",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "about",
    kind: "about",
    label: "Provenance",
    component: "Provenance",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/About/Provenance").then((m) => m.Provenance),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programmes",
    component: "Programmes",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Programmes/Programmes").then((m) => m.Programmes),
  },
  {
    id: "features",
    kind: "features",
    label: "Craft",
    component: "Craft",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Craft/Craft").then((m) => m.Craft),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Numbers",
    component: "Numbers",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Numbers/Numbers").then((m) => m.Numbers),
  },
  {
    id: "team",
    kind: "team",
    label: "Brigade",
    component: "Brigade",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Brigade/Brigade").then((m) => m.Brigade),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "House",
    component: "House",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/House/House").then((m) => m.House),
  },
  {
    id: "team-2",
    kind: "team",
    label: "Board",
    component: "Board",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Board/Board").then((m) => m.Board),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Voices",
    component: "Voices",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Voices/Voices").then((m) => m.Voices),
  },
  {
    id: "faq",
    kind: "faq",
    label: "Questions",
    component: "Questions",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Questions/Questions").then((m) => m.Questions),
  },
  {
    id: "admission",
    kind: "admission",
    label: "Reservations",
    component: "Reservations",
    slices: [],
    load: () => import("@edn/site-themes/Theme/Theme-19/components/Reservations/Reservations").then((m) => m.Reservations),
  },
  ],
};

export default manifest;
