// AUTO-GENERATED by scripts/generate-studio-manifests.mjs.
// Derived from src/Theme/Theme-2/index.tsx — do not edit by hand.

import type { ThemeManifest } from "@/studio/types";

const manifest: ThemeManifest = {
  id: "theme-2",
  frameClassName: "relative min-h-screen bg-background text-foreground",
  mainClassName: "relative z-10",
  sections: [
  {
    id: "hero",
    kind: "hero",
    label: "Hero",
    component: "Hero",
    slices: ["slider"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Hero/Hero").then((m) => m.Hero),
  },
  {
    id: "partners",
    kind: "partners",
    label: "Partners",
    component: "Partners",
    slices: ["client"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Partners/Partners").then((m) => m.Partners),
  },
  {
    id: "about",
    kind: "about",
    label: "About",
    component: "About",
    slices: ["aboutUs"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/AboutUs/About").then((m) => m.About),
  },
  {
    id: "statistics",
    kind: "statistics",
    label: "Stats",
    component: "Stats",
    slices: ["statistics"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Statistics/Statistics").then((m) => m.Stats),
  },
  {
    id: "programs",
    kind: "programs",
    label: "Programs",
    component: "Programs",
    slices: ["program"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Programs/Programs").then((m) => m.Programs),
  },
  {
    id: "admission",
    kind: "admission",
    label: "Admission",
    component: "Admission",
    slices: ["layout"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Admission/Admission").then((m) => m.Admission),
  },
  {
    id: "team",
    kind: "team",
    label: "Faculty",
    component: "Faculty",
    slices: ["team","board"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Faculty/Faculty").then((m) => m.Faculty),
  },
  {
    id: "news",
    kind: "news",
    label: "Blog",
    component: "Blog",
    slices: ["layout","blog","news"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Blog/Blog").then((m) => m.Blog),
  },
  {
    id: "testimonials",
    kind: "testimonials",
    label: "Testimonials",
    component: "Testimonials",
    slices: ["testimonial"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Testimonials/Testimonials").then((m) => m.Testimonials),
  },
  {
    id: "gallery",
    kind: "gallery",
    label: "Gallery",
    component: "Gallery",
    slices: ["album"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Gallery/Gallery").then((m) => m.Gallery),
  },
  {
    id: "facilities",
    kind: "facilities",
    label: "Facilities",
    component: "Facilities",
    slices: ["facility"],
    load: () => import("@edn/site-themes/Theme/Theme-2/components/Facilities/Facilities").then((m) => m.Facilities),
  },
  ],
};

export default manifest;
